### ISSUE TITLE
Float Filter isn't exposed

### ISSUE THREAD

**Issue by Dwarph** [DarioMazzanti/OneEuroFilterUnity#4]
The functionality for float isn't exposed as OneEuroFilter isn't public.

In addition to this, the UpdateParams method doesn't include default parameters for non-frequency parameters.

**Comment by DarioMazzanti** [comment]
Thanks for the Pull Request, merged! : )

**Comment by Dwarph** [comment]
Awesome, cheers! Great work with this - it's super useful.

**Comment by DarioMazzanti** [comment]
Happy to hear that, thank you!
